import "./Terms.css";


function Terms() {
    return(
        <div class="container">
    
    
    <div class="left">
        <h2>Login</h2>
        <p>Get access to your Orders<br/><br/>Wishlist and<br/><br/> Recommendations</p>
    </div>
        <div class="right">
            <h6>Shopsy Terms of Use</h6>
            <p>This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable and the amended provisions 
                pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a 
                computer system and does not require any physical or digital signatures.</p>

            <p>The Terms of Use is a legal document and creates an agreement between You and <b>Flipkart Internet Private Limited</b>, a company incorporated under the 
                Companies Act, 1956, having its registered office at Buildings Alyssa, Begonia & Clover, Embassy Tech Village, Outer Ring Road, Devarabeesanahalli 
                Village, Bengaluru - 560103, Karnataka, India, ("<b>Company</b>") for the access and use of the Shopsy website/mobile app ("<b>Platform</b>"). The Company owns 
                and operates www.shopsy.in including the related mobile site and mobile application (hereinafter referred to as "<b>Shopsy Platform</b>").</p>

            <p>For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a 
                buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. Shopsy allows the 
                User to surf the Platform or make purchases without registering on the Platfnpm run devorm. The terms "We", "Us", "Our" shall mean Shopsy Platform.</p>
            
            <p>ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE 
                TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, you also accept and agree to be bound by Shopsy 
                Policies (including but not limited to Privacy Policy available at Privacy) as amended from time to time.</p>

            <p>Membership Eligibility</p>

            <p>Transaction on the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are 
                "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the 
                Platform. If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and 
                prior consent/ permission of a parent or legal guardian.</p>

            <p>As a minor if you wish to transact on the Platform, such a transaction on the Platform may be made by your legal guardian or parents. Shopsy reserves 
                the right to terminate your membership and / or refuse to provide you with access to the Platform if it is brought to Shopsy's notice or if it is 
                discovered that You are under the age of 18 years and transacting on the Platform.</p>

            <p>Your Account and Registration Obligations</p>

            <p>If You use the Platform, you shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for 
                all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current 
                or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with 
                the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform and refuse to 
                provide You with access to the Platform.</p>

            <p>Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Platform. It is your responsibility to ensure that your 
                mobile phone number and your email address is up to date on the Platform at all times. You agree to notify Us promptly if your mobile phone number 
                or e-mail address changes by updating the same on the Platform through a one-time password verification.</p>

            <p>You agree that Shopsy shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your 
                Account in cases, including, where You have failed to update Your revised mobile phone number and/or e-mail address on the Website Platform.</p>

            <p>If You share or allow others to have access to Your account on the Platform ("Account"), by creating separate profiles under Your Account, or otherwise, 
                they will be able to view and access Your Account information. You shall be solely liable and responsible for all the activities undertaken under Your 
                Account, and any consequences there from.</p>

            <p>You must maintain confidentiality of the account information and for all the activities that occur under Your account. You must not share your login 
                details, i.e., username and password of Your account with any other person, else it would be considered breach of this Terms of Use.</p>

            <p>You agree to: (a) ensure that You successfully log out from Your account at the end of each session; and (b) immediately notify Shopsy of any 
                unauthorized use of Your account. If there is reason to believe that there is likely to be a breach of security or misuse of Your account, We may 
                request You to change the password or we may suspend Your account without any liability to Shopsy, for such period of time as we deem appropriate in 
                the circumstances. We shall not be liable for any loss or damage arising from Your failure to comply with this provision.</p>
            
            <p>Communications</p>

            <p>When You use the Platform or send emails or other data, information or communication to us, you agree and understand that You are communicating with 
                Us through electronic records, and You consent to receive communications via electronic records from Us periodically and as and when required. We may 
                communicate with you by email or by such other mode of communication, electronic or otherwise.</p>

            <p>Platform for Transaction and Communication</p>

            <p>The Platform enables the Buyer and Seller to transact on the Platform. Shopsy is not and cannot be a party to or control in any manner any transaction 
                between the Platform's Users.</p>
  
            <p>Henceforward:</p>

            <ul class="outer">
                <li>All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone. The commercial/contractual terms include without 
                    limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services 
                    and after sales services related to products and services. Shopsy does not have any control or does not determine or advise or in any way involve 
                    itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers. All discounts and offers (including 
                    exchange offer) are by the Seller/Brand and not by Shopsy.</li><br/>

                    <li>Placement of order by a Buyer with Seller on the Platform is an offer to buy the product(s) from the Buyer to the Seller and it shall not be 
                        construed as Seller's acceptance of Buyer's offer to buy the product(s) ordered. The Seller retains the right to cancel any such order placed 
                        by the Buyer, at its sole discretion and the Buyer shall be intimated of the same by way of an email/SMS. Any transaction price paid by the 
                        Buyer in case of such cancellation by Seller, shall be refunded to the Buyer. Further, the Seller may cancel an order wherein the quantities 
                        exceed the typical individual consumption. This applies both to the number of products ordered within a single order and the placing of several 
                        orders for the same product where the individual orders comprise a quantity that exceeds the typical individual consumption. What comprises a 
                        typical individual's consumption quantity limit shall be based on various factors and at the sole discretion of the Seller and may vary from 
                        individual to individual.</li><br/>

                    <li>Shopsy does not make any representation or warranty as to specifics (such as quality, value, salability, etc.) of the products or services 
                        proposed to be sold or offered to be sold or purchased on the Platform. Shopsy does not implicitly or explicitly support or endorse the sale 
                        or purchase of any products or services on the Platform. Shopsy accepts no liability for any errors or omissions, whether on behalf of itself 
                        or third parties.</li><br/>

                    <li>Shopsy is not responsible for any non-performance or breach of any contract entered into between Buyers and Sellers. Shopsy cannot and does not 
                        guarantee that the concerned Buyers and/or Sellers will perform any transaction concluded on the Platform. Shopsy shall not and is not required 
                        to mediate or resolve any dispute or disagreement between Buyers and Sellers.</li><br/>

                    <li>Shopsy does not make any representation or warranty as to the item-specifics (such as legal title, creditworthiness, identity, etc.) of any of 
                        its Users. You are advised to independently verify the Bonafide's of any particular User that You choose to deal with on the Platform and use 
                        Your best judgment in that behalf.</li><br/>

                    <li>Shopsy does not at any point of time during any transaction between Buyer and Seller on the Platform come into or take possession of any of the 
                        products or services offered by Seller nor does it at any point gain title to or have any rights or claims over the products or services offered 
                        by Seller to Buyer.</li><br/>

                    <li>At no time shall Shopsy hold any right, title or interest over the products nor shall Shopsy have any obligations or liabilities in respect of 
                        such contract entered into between Buyers and Sellers. Shopsy is not responsible for unsatisfactory or delayed performance of services or damage 
                        or delays as a result of products which are out of stock, unavailable or back ordered.</li><br/>

                    <li>The Platform is only a platform that can be utilized by Users to reach a larger base to buy and sell products or services. Shopsy is only 
                        providing a platform for communication, and it is agreed that the contract for sale of any of the products or services shall be a strictly 
                        bipartite contract between the Seller and the Buyer.</li>
            
            </ul><br/>

                <p>At no time shall Shopsy hold any right, title or interest over the products nor shall Shopsy have any obligations or liabilities in respect of such 
                    a contract.</p>

                <p>Shopsy is not responsible for unsatisfactory or delayed performance of services or damage or delays as a result of products which are out of stock, 
                    unavailable or back ordered.</p>

                <p>Select products offered by sellers may be eligible for business purchases on the Platform.</p>

                <ul class="outer">
                    <li>Upon Your purchase of product(s) eligible for business purchases, you may be able to avail the benefits of GST input tax credit. Accordingly, 
                        at your request, an invoice containing the GSTIN as provided by You ("Tax Invoice") shall be issued to You by the Seller(s) selling such 
                        products.</li>
                </ul><br/>

                <ul class="inner">

                <li>GST invoice will have, inter alia, the following details printed on it: -GSTIN associated with your registered business, as provided by you.</li><br/>

                <li>Entity name of your registered business, as provided by you</li><br/>

                <li>Not all products are eligible for business purchases on the Platform and the same is solely at the discretion of the Sellers. You will be able to 
                    view the 
                    eligibility of Tax Invoice on the product page on the Platform.</li><br/>

                <li>Purchases on the Platform must only be for end consumption. Users must not use products purchased on the Platform for any commercial, promotional, 
                    resale or further distribution purposes.</li><br/>

                <li>For seamless availment of input tax credit, kindly mention the delivery address as the address which is mentioned as the registered place of business 
                    as per the records of GST authority. Please note that the availment of input tax credit is subject to the provisions of the GST Act and rules.</li><br/>

                <li>The delivery and billing addresses will be required to be the same, please note that input tax credit will be denied by GST authority if the delivery address 
                    and GSTIN in the GST invoice are of different states.</li><br/>

                <li>If GSTIN and/or business entity details are not provided by You, it will be presumed that it is a personal purchase and not a business purchase.</li><br/>

                <li>Shopsy is not responsible to verify the correctness of the GSTIN and/or entity name provided by You and You shall be entirely responsible to provide 
                    the accurate details.</li><br/>

                <li>Shopsy and Seller shall not entertain any request for any revision in the GST Invoice. Shopsy and Seller shall not be liable for Your default 
                    including for 
                    reasons associated with details provided by You.</li><br/>

                <li>Shopsy will not be liable in case You are not able to avail input tax credit or if input tax credit is denied to You for any reason whatsoever.</li><br/>

                <li>You shall be solely liable for all compliances required under applicable laws.</li><br/>

                <li>You agree to indemnify and hold Shopsy and Seller harmless from all losses, claims, costs, expenses, suits, proceedings, or any other liability 
                    including any third-party claims (including any penalties imposed by governmental authorities) arising out of or in connection with (1) the GSTIN 
                    and/or entity name provided by you or the input tax credit claimed by you or your use or misuse of the GST Invoice and (2) your non-compliance with 
                    the applicable laws or (3) your use ormisuse of any third-party's details including GSTIN.</li><br/>

                <li>Shopsy has the right to not allow business purchases on the Platform to You if a fraudulent activity is identified.</li><br/>

                <li>Seller reserves the right not to issue Tax Invoice or issue a credit note against an already issued Tax Invoice to cancel the transaction, if any fraudulent 
                    activity is identified.</li><br/>
            </ul>
            <ul class="outer">

                <li>You shall independently agree upon the manner and terms and conditions of delivery, payment, insurance etc. with the seller(s) that You transact 
                    with.</li>
            </ul><br/>
            <p>Disclaimer: Pricing on any product(s) as is reflected on the Platform may be due to some technical issue, typographical error or product information 
                published by seller may be incorrectly reflected and in such an event the seller may cancel such your order(s).</p>
            
                <ul class="outer">
                    <li>You release and indemnify Shopsy and/or any of its officers and representatives from any cost, damage, liability or other consequence of any 
                        of the actions of the Users of the Platform and specifically waive any claims that you may have in this regard under any applicable law. 
                        Notwithstanding its reasonable efforts in that behalf, Shopsy cannot take responsibility or control the information provided by other Users 
                        which is made available on the Platform. You may find other User's information to be offensive, harmful, inconsistent, inaccurate, or deceptive. 
                        Please use caution and practice safe trading when using the Platform.</li>
                </ul><br/>
            
            <p>Please note that there could be risks in dealing with underage persons or people acting under false pretense.</p>

            <p>Charges</p>

            <p>Shopsy may charge a nominal fee for browsing and buying on the Platform. Shopsy reserves the right to change its Fee Policy from time to time. 
                In particular, Shopsy may at its sole discretion introduce new services/fees and modify some or all of the existing services/fees offered on 
                the Platform. In such an event, Shopsy reserves the right to introduce fees for the new services offered or amend/introduce fees for existing/new 
                services, as the case may be. Changes to the Fee Policy shall be posted on the Platform and such changes shall automatically become effective 
                immediately after they are posted on the Platform. Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible 
                for compliance of all applicable laws including those in India for making payments to Shopsy Internet Private Limited.</p>

            <p>Use of the Platform</p>

            <p>You agree, undertake and confirm that Your use of Platform shall be strictly governed by the following binding principles:</p>

            <ul class="outer">
                <li>You shall not host, display, upload, modify, publish, transmit, update or share any information which:</li><br/>
            </ul><br/>

            <p>(a) belongs to another person and to which You do not have any right to.</p>

            <p>(b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libellous, invasive of 
            another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money 
            laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully 
            harassing including but not limited to "indecent representation of women" within the meaning of the Indecent 
            Representation of Women (Prohibition) Act, 1986;</p>

            <p>(c) is misleading in any way.</p>

            <p>(d) is patently offensive to the online community, such as sexually explicit content, or content that promotes 
                obscenity, pedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual.</p>

            <p>(e) harasses or advocates harassment of another person.</p>

            <p>(f) involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming".</p>

            <p>(g) promotes illegal activities or conduct that are abusive, threatening, obscene, defamatory or libelous.</p>

            <p>(h) infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, 
            rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical 
            address or phone number) or rights of publicity].</p>

            <p>(i) promotes an illegal or unauthorized copy of another person's copyright work (see "Copyright complaint" below for 
            instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer 
            programs or links to them, providing information to circumvent manufacture-installed copy-protect devices.</p>

            <p>(j) contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page).</p>

            <p>(k) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone.</p>

            <p>(l) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or 
            creating computer viruses.</p>

            <p>(m) contains video, photographs, or images of another person (with a minor or an adult).</p>

            <p>(n) tries to gain unauthorized access or exceed the scope of authorized access to the Platform or to profiles, blogs, communities, account information, 
            bulletins, friend request, or other areas of the Platform or solicits passwords or personal identifying information for commercial or unlawful purposes 
            from other users.</p>

            <p>(o) engages in commercial activities and/or sales without Our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, 
            or the buying or selling of "virtual" products related to the Platform. Throughout this Terms of Use, Shopsy 's prior written consent means a communication 
            coming from Shopsy 's Legal Department, specifically in response to Your request, and specifically addressing the activity or conduct for which You seek 
            authorization.</p>

            <p>(p) solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal.</p>

            <p>(q) interferes with another user's use and enjoyment of the Platform or any other individual's user and enjoyment of similar services.</p>

            <p>(r) refers to any platform or URL that, in Our sole discretion, contains material that is inappropriate for the Platform or any other Platform, contains 
            content that would be prohibited or violates the letter or spirit of these Terms of Use.</p>

            <p>(s) harm minors in any way.</p>

            <p>(t) infringes on any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall 
            not be fraudulent or involve the sale of counterfeit or stolen products.</p>

            <p>(u) violates any law for the time being in force.</p>

            <p>(v) deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing 
            in nature.</p>

            <p>(w) impersonate another person.</p>

            <p>(x) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer 
            resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally 
            interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;</p>

            <p>(y) threatens the unity, integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement 
            to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.</p>

            <p>(z) shall not be false, inaccurate or misleading.</p>

            <p>(aa) shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted 
            in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.</p>

            <p>(ab) shall not create liability for Us or cause Us to lose (in whole or in part) the services of Our internet service provider ("ISPs") or other 
            suppliers.</p>

            <ul class="outer">
                <li>You shall not use any "deep-link", "page-scrape", "robot", "spider" or other automatic device, program, algorithm or methodology, or any similar or 
                equivalent manual process, to access, acquire, copy or monitor any portion of the Platform or any Content, or in any way reproduce or circumvent the 
                navigational structure or presentation of the Platform or any Content, to obtain or attempt to obtain any materials, documents or information through 
                any means not purposely made available through the Platform. We reserve Our right to bar any such activity.</li><br/>
<li>You shall not attempt to gain unauthorized access to any portion or feature of the Platform, or any other systems or networks connected to the Platform or to any 
server, computer, network, or to any of the services offered on or through the Platform, by hacking, password "mining" or any other illegitimate means.</li><br/>
<li>You should not probe, scan or test the vulnerability of the Platform or any network connected to the Platform nor breach the security or authentication measures on 
the Platform, or any network connected to the Platform. You may not reverse look-up, trace or seek to trace any information on any other User of or visitor to Platform, 
or any other customer, including any account on the Platform not owned by You, to its source, or exploit the Platform or any service or information made available or 
offered by or through the Platform, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, 
other than Your own information, as provided for by the Platform.</li><br/>
<li>You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand name or domain name used by Us including the terms 
    Shopsy, shopsy.com, or otherwise engage in any conduct or action that might tarnish the image or reputation or sellers on platform or otherwise tarnish or dilute 
    any Shopsy 's trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by us. You agree 
    that You will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Platform or Shopsy 's systems or 
    networks, or any systems or networks connected to Shopsy.</li><br/>
<li>You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Platform or any transaction being 
    conducted on the Platform, or with any other person's use of the Platform.</li><br/>
<li>You may not forget headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal You send to Us on or through the 
    Platform or any service offered on or through the Platform. You may not pretend that You are, or that You represent, someone else, or impersonate any other 
    individual or entity.</li><br/>
<li>You may not use the Platform or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal 
    activity or other activity which infringes the rights of Shopsy and / or others.</li><br/>
<li>shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules thereunder as applicable and as amended 
    from time to time and also all applicable Domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in 
    Force) and International Laws, Foreign Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Sales Tax/VAT, Income Tax, Octroi, Service 
    Tax, Central Excise, Custom Duty, Local Levies) regarding Your use of Our service and Your listing, purchase, solicitation of offers to purchase, and sale of 
    products or services. You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange 
    control laws or regulations for the time being in force.</li><br/>
<li>Solely to enable Us to use the information You supply Us with, so that we are not violating any rights You might have in Your Information, You agree to grant Us a 
    non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights 
    or any other rights You have in Your Information, in any media now known or not currently known, with respect to Your Information. We will only use Your information 
    in accordance with the Terms of Use and Privacy Policy applicable to use of the Platform.</li><br/>
<li>From time to time, you shall be responsible for providing information relating to the products or services proposed to be sold by You. In this connection, you 
    undertake that all such information shall be accurate in all respects. You shall not exaggerate or over emphasize the attributes of such products or services so 
    as to mislead other Users in any manner.</li><br/>
<li>You shall not engage in advertising to, or solicitation of, other Users of the Platform to buy or sell any products or services, including, but not limited to, 
    products or services related to that being displayed on the Platform or related to us. You may not transmit any chain letters or unsolicited commercial or junk 
    email to other Users via the Platform. It shall be a violation of these Terms of Use to use any information obtained from the Platform in order to harass, abuse, 
    or harm another person, or in order to contact, advertise to, solicit, or sell to another person other than Us without Our prior explicit consent. In order to 
    protect Our Users from such advertising or solicitation, we reserve the right to restrict the number of messages or emails which a user may send to other Users in 
    any 24-hour period which We deems appropriate in its sole discretion. You understand that We have the right at all times to disclose any information (including the 
    identity of the persons providing information or materials on the Platform) as necessary to satisfy any law, regulation or valid governmental request. This may 
    include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in 
    response to a lawful court order or subpoena. In addition, We can (and You hereby expressly authorize Us to) disclose any information about You to law enforcement 
    or other government officials, as we, in Our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible 
    crimes, especially those that may involve personal injury.</li>
            </ul><br/>

            <p>We reserve the right, but has no obligation, to monitor the materials posted on the Platform. Shopsy shall have the right to remove or edit any content 
                that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use. Notwithstanding 
                this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE PLATFORM AND IN YOUR PRIVATE MESSAGES. Please be advised that 
                such Content posted does not necessarily reflect Shopsy's views. In no event shall Shopsy assume or have any responsibility or liability for any Content 
                posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the Platform. You hereby represent and warrant 
                that You have all necessary rights in and to all Content which You provide and all information it contains and that such Content shall not infringe any 
                proprietary or other rights of third parties or contain any libelous, tortious, or otherwise unlawful information.</p>

                <ul class="outer">
                    <li>Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Platform, including 
                        payment and delivery of related products or services, and any other terms, conditions, warranties or representations associated with such 
                        dealings, are solely between You and such advertiser. We shall not be responsible or liable for any loss or damage of any sort incurred as 
                        the result of any such dealings or as the result of the presence of such advertisers on the Platform.</li><br/>
                    <li>It is possible that other users (including unauthorized users or "hackers") may post or transmit offensive or obscene materials on the Platform 
                        and that You may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information 
                        about You due to your use of the Platform, and that the recipient may use such information to harass or injure You. We do not approve of such 
                        unauthorized uses, but by using the Platform You acknowledge and agree that We are not responsible for the use of any personal information that 
                        You publicly disclose or share with others on the Platform. Please carefully select the type of information that You publicly disclose or share 
                        with others on the Platform.</li><br/>
                    <li>Shopsy shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on 
                        your own or through group/s of people, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).</li><br/>
                </ul>

                <p>Contents Posted on Platform</p>

<p>All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music and artwork (collectively, "Content"), is a third-party user 
    generated content and Shopsy has no control over such third-party user generated content as Shopsy is merely an intermediary for the purposes of this Terms of Use.</p>

<p>Except as expressly provided in these Terms of Use, no part of the Platform and no Content may be copied, reproduced, republished, uploaded, posted, publicly 
    displayed, encoded, translated, transmitted or distributed in any way (including "mirroring") to any other computer, server, Platform or other medium for 
    publication or distribution or for any commercial enterprise, without Shopsy's express prior written consent.</p>

<p>You may use information on the products and services purposely made available on the Platform for downloading, provided that You: (1) do not remove any proprietary 
    notice language in all copies of such documents, (2) use such information only for your personal, non-commercial informational purpose and do not copy or post such 
    information on any networked computer or broadcast it in any media, (3) make no modifications to any such information, and (4) do not make any additional 
    representations or warranties relating to such documents.</p>

<p>You shall be responsible for any notes, messages, emails, reviews, ratings, billboard postings, photos, drawings, profiles, opinions, ideas, images, videos, 
    audio files or other materials or information posted or transmitted to the Platform (collectively, "Content"). Such Content will become Our property, and You 
    grant Us the worldwide, perpetual and transferable rights in such Content. We shall be entitled to, consistent with Our Privacy Policy as adopted in accordance 
    with applicable law, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in 
    any media whether now known or hereafter devised, including the creation of derivative works that may include the Content You provide. You agree that any Content 
    You post may be used by us, consistent with Our Privacy Policy and Rules of Conduct on Site as mentioned herein, and You are not entitled to any payment or other 
    compensation for such use.</p>

<p>SOME CONTENT OFFERED ON THE PLATFORM MAY NOT BE SUITABLE FOR SOME VIEWERS AND THEREFORE VIEWER DISCRETION IS ADVISED. ALSO, SOME CONTENT OFFERED ON THE PLATFORM 
    MAY NOT BE APPROPRIATE FOR VIEWERSHIP BY CHILDREN. PARENTS AND/OR LEGAL GUARDIANS ARE ADVISED TO EXERCISE DISCRETION BEFORE ALLOWING THEIR CHILDREN AND/OR WARDS 
    TO ACCESS CONTENT ON THE PLATFORM.</p>

<p>Privacy</p>

<p>We view protection of Your privacy as a very important principle. We understand clearly that You and Your Personal Information is one of Our most important assets. 
    We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on 
    computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 
    and Rules there under. Our current Privacy Policy is available at Privacy. if You object to Your Information being transferred or used in this way, please do not 
    use the Platform.</p>

<p>We may share personal information with our other corporate entities and affiliates. These entities and affiliates may market to you as a result of such sharing 
    unless you explicitly opt-out.</p>

<p>We may disclose personal information to third parties. This disclosure may be required for us to provide you access to our Services, to comply with our legal 
    obligations, to enforce our User Agreement, to facilitate our marketing and advertising activities, or to prevent, detect, mitigate, and investigate fraudulent 
    or illegal activities related to our Services. We do not disclose your personal information to third parties for their marketing and advertising purposes without 
    your explicit consent.</p>

<p>We may disclose personal information if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, 
    court orders, or other legal process. We may disclose personal information to law enforcement offices, third party rights owners, or others in the good faith 
    belief that such disclosure is reasonably necessary to: enforce our Terms or Privacy Policy; respond to claims that an advertisement, posting or other content 
    violates the rights of a third party; or protect the rights, property or personal safety of our users or the general public.</p>

<p>We and our affiliates will share / sell some or all of your personal information with another business entity should we (or our assets) plan to merge with, or be 
    acquired by that business entity, or re-organization, amalgamation, restructuring of business. Should such a transaction occur, other business entity (or the new 
    combined entity) will be required to follow this privacy policy with respect to your personal information.</p>

<p>Disclaimer of Warranties and Liability</p>

<p>This Platform, all the materials and products (including but not limited to software) and services, included on or otherwise made available to You through this site 
    are provided on "as is" and "as available" basis without any representation or warranties, express or implied except otherwise specified in writing. Without 
    prejudice to the forgoing paragraph, Shopsy does not warrant that:</p>

<p>This Platform will be constantly available, or available at all; or</p>

<p>The information on this Platform is complete, true, accurate or non-misleading.</p>

<p>Shopsy will not be liable to You in any way or in relation to the Contents of, or use of, or otherwise in connection with, the Platform. Shopsy does not warrant 
    that this site; information, Content, materials, product (including software) or services included on or otherwise made available to You through the Platform; 
    their servers; or electronic communication sent from Us are free of viruses or other harmful components.</p>

<p>Nothing on Platform constitutes, or is meant to constitute, advice of any kind. All the Products sold on Platform are governed by different state laws and if Seller 
    is unable to deliver such Products due to implications of different state laws, Seller will return or will give credit for the amount (if any) received in advance 
    by Seller from the sale of such Product that could not be delivered to You.</p>

<p>You will be required to enter a valid phone number while placing an order on the Platform. By registering Your phone number with us, you consent to be contacted by 
    Us via phone calls, SMS notifications, mobile applications and/or any other electronic mode of communication in case of any order or shipment or delivery related 
    updates.</p>

<p>Payment</p>

<p>While availing any of the payment method/s available on the Platform, we will not be responsible or assume any liability, whatsoever in respect of any loss or damage 
    arising directly or indirectly to You due to:</p>

    <ul class="outer">
        <li>Lack of authorization for any transaction/s, or</li><br/>
<li> the pre-set limit mutually agreed by You and between "Bank/s", or</li><br/>
<li>Any payment issues arising out of the transaction, or</li><br/>
<li>Decline of transaction for any other reason/s</li><br/>
    </ul>

    <p>All payments made against the purchases/services on Platform by you shall be compulsorily in Indian Rupees acceptable in the Republic of India. Platform will 
        not facilitate transaction with respect to any other form of currency with respect to the purchases made on Platform.</p>

<p>Before shipping / delivering your order to you, Seller may request you provide supporting documents (including but not limited to Govt. issued ID and address proof) 
    to establish the ownership of the payment instrument used by you for your purchase. This is done in the interest of providing a safe online shopping environment to 
    Our Users.</p>

    <p>Further:</p>

    <ul class="outer">
       <li>Transactions, Transaction Price and all commercial terms such as Delivery, Dispatch of products and/or services are as per principal-to-principal 
        bipartite contractual obligations between Buyer and Seller and payment facility is merely used by the Buyer and Seller to facilitate the completion 
        of the Transaction. Use of the payment facility shall not render Shopsy liable or responsible for the non-delivery, non-receipt, non-payment, damage, 
        breach of representations and warranties, non-provision of after-sales or warranty services or fraud as regards the products and /or services listed 
        on Shopsy 's Platform.</li><br/>
<li>You have specifically authorized Shopsy or its service providers to collect, process, facilitate and remit payments and / or the Transaction Price electronically 
or through Cash on Delivery to and from other Users in respect of transactions through Payment Facility. Your relationship with Shopsy is on a principal to principal 
basis and by accepting these Terms of Use you agree that Shopsy is an independent contractor for all purposes, and does not have control of or liability for the 
products or services that are listed on Shopsy 's Platform that are paid for by using the Payment Facility. Shopsy does not guarantee the identity of any User, nor 
does it ensure that a Buyer or a Seller will complete a transaction.</li><br/>
<li>You understand, accept and agree that the payment facility provided by Shopsy is neither a banking nor financial service but is merely a facilitator providing an 
    electronic, automated online electronic payment, receiving payment through Cash-on delivery, collection and remittance facility for the Transactions on the Shopsy 
    Platform using the existing authorized banking infrastructure and Credit Card payment gateway networks. Further, by providing Payment Facility, Shopsy is neither 
    acting as trustees nor acting in a fiduciary capacity with respect to the Transaction or the Transaction Price.</li><br/>
    </ul>

    <p>Payment Facility for Buyers:</p>

    <ul class="outer">
        <li>You, as a Buyer, understand that upon initiating a Transaction You are entering into a legally binding and enforceable contract with the Seller to purchase 
            the products and /or services from the Seller using the Payment Facility, and You shall pay the Transaction Price through Your Issuing Bank to the Seller 
            using Payment Facility.</li><br/>
<li>You, as a Buyer, may agree with the Seller through electronic communication and electronic records and using the automated features as may be provided by Payment 
    Facility on any extension / increase in the Dispatch and/or Delivery time and the Transaction shall stand amended to such extent. Any such extension / increase of 
    Dispatch / Delivery time or subsequent novation / variation of the Transaction should be in compliance with Payment Facility Rules and Policies.</li><br/>
<li>You, as a Buyer, shall electronically notify Payment Facility using the appropriate Shopsy Platform features immediately upon Delivery or non- Delivery within the 
    time period as provided in Policies. Non notification by You of Delivery or non- Delivery within the time period specified in the Policies shall be construed as a 
    deemed Delivery in respect of that Transaction. In case of Cash- On Delivery transactions, Buyer is not required to confirm the receipt of products or services.</li><br/>
<li>You, as a Buyer, shall be entitled to claim a refund of the Transaction Price (as Your sole and exclusive remedy) in case You do not receive the Delivery within the 
    time period agreed in the Transaction or within the time period as provided in the Policies, whichever is earlier. In case you do not raise a refund claim using 
    Platform features within the stipulated time than this would make You ineligible for a refund.</li><br/>
<li>You, as a Buyer, understand that the Payment Facility may not be available in full or in part for certain category of products and/or services and/or Transactions 
    as mentioned in the Policies and hence You may not be entitled to a refund in respect of the Transactions for those products and /or services</li>
<li>Except for Cash on Delivery transactions, a refund, if any, shall be made at the same Issuing Bank from where Transaction Price was received, or through any other 
    method available on the Platform, as chosen by You.</li><br/>
<li>For Cash on Delivery transactions, refunds, if any, will be made via electronic payment transfers.</li><br/>
<li>Refund shall be made in Indian Rupees only and shall be equivalent to the Transaction Price received in Indian Rupees.</li><br/>
<li>For electronics payments, refund shall be made through payment facility using NEFT / RTGS or any other online banking / electronic funds transfer system approved 
    by Reserve Bank India (RBI).</li><br/>
<li>Refunds may be supported for select banks. Where a bank is not supported for processing refunds, you will be required to share alternate bank account details with 
    us for processing the refund.</li><br/>
<li>Refund shall be conditional and shall be with recourse available to Shopsy in case of any misuse by Buyer.</li><br/>
<li>We may also request you for additional documents for verification.</li><br/>
<li>Refund shall be subject to Buyer complying with Policies.</li><br/>
<li>Shopsy reserves the right to impose limits on the number of Transactions or Transaction Price which Shopsy may receive from on an individual Valid Credit/Debit/ 
    Cash Card / Valid Bank Account/ and such other infrastructure or any other financial instrument directly or indirectly through payment aggregator or through any 
    such facility authorized by Reserve Bank of India to provide enabling support facility for collection and remittance of payment or by an individual Buyer during 
    any time period, and reserves the right to refuse to process Transactions exceeding such limit.</li><br/>
<li>Shopsy reserves the right to refuse to process Transactions by Buyers with a prior history of questionable charges including without limitation breach of any 
    agreements by Buyer with Shopsy or breach/violation of any law or any charges imposed by Issuing Bank or breach of any policy.</li><br/>
<li>Shopsy may do such checks as it deems fit before approving the receipt of/Buyer's commitment to pay (for Cash on Delivery transactions) Transaction Price from the 
    Buyer for security or other reasons at the discretion of Shopsy. As a result of such checks, if Shopsy is not satisfied with the creditability of the Buyer or 
    genuineness of the Transaction or other reasons at its sole discretion, Shopsy shall have the right to reject the receipt of / Buyer's commitment to pay Transaction 
    Price. For avoidance of doubt, it is hereby clarified that the 'Cash on Delivery' feature for payment, may be disabled for certain account users, at the sole 
    discretion of Shopsy.</li><br/>
<li>Shopsy may delay notifying the payment confirmation i.e., informing Seller to dispatch, if Shopsy deems suspicious or for Buyers conducting high transaction 
    volumes to ensure safety of the Transaction and Transaction Price. In addition, Shopsy may hold Transaction Price and Shopsy may not inform Seller to Dispatch 
    or remit Transaction Price to law enforcement officials (instead of refunding the same to Buyer) at the request of law enforcement officials or in the event the 
    Buyer is engaged in any form of illegal activity.</li><br/>
<li>The Buyer and Seller acknowledge that Shopsy will not be liable for any damage, interests or claims etc. resulting from not processing a Transaction/Transaction 
    Price or any delay in processing a Transaction/Transaction Price which is beyond control of Shopsy.</li><br/>
    </ul>

    <p>Compliance with Laws:</p>

    <ul class="outer">
        <li>As required by applicable law, if the Customer makes a purchase of an amount equal to or above INR 2, 00, 000.00/- the Customer will be required to upload
             a scanned copy of his/her PAN card on the Platform, within 4 days of making the purchase, failing which, the purchase made by the Customer will be 
             cancelled. The requirement to submit the PAN card arises only once and if it has been submitted already by the Customer, it need not be submitted again. 
             The order of the Customer shall stand cancelled if there is a discrepancy between the name of the Customer and the name on the PAN Card.</li><br/>
<li>Buyer and Seller shall comply with all the applicable laws (including without limitation Foreign Exchange Management Act, 1999 and the rules made and notifications 
    issued there under and the Exchange Control Manual as may be issued by Reserve Bank of India from time to time, Customs Act, Information and Technology Act, 2000 
    as amended by the Information Technology (Amendment) Act 2008, Prevention of Money Laundering Act, 2002 and the rules made there under, Foreign Contribution 
    Regulation Act, 1976 and the rules made there under, Income Tax Act, 1961 and the rules made there under, Export Import Policy of government of India) applicable 
    to them respectively for using Payment Facility and Shopsy Platform.</li><br/>
    </ul>

    <p>Buyer's arrangement with Issuing Bank:</p>

    <ul class="outer">
        <li>All valid Credit / Debit/ Cash Card/ and other payment instruments are processed using a Credit Card payment gateway or appropriate payment system 
            infrastructure and the same will also be governed by the terms and conditions agreed between the Buyer and the respective Issuing Bank and payment 
            instrument issuing company.</li><br/>
<li>All Online Bank Transfers from Valid Bank Accounts are processed using the gateway provided by the respective Issuing Bank which support Payment Facility to 
    provide these services to the Users. All such Online Bank Transfers on Payment Facility are also governed by the terms and conditions agreed to between Buyer 
    and the respective Issuing Bank.</li><br/>
    </ul>

    <p>Customer Conduct</p>

    <p>Terms:</p>
    <p>A) Shopsy fosters diversity, inclusion, equity and protect the individuals who are engaged with us as delivery partners from any discrimination on grounds 
        such as race, social origin, caste, ethnicity, nationality, gender, gender identity and expression, sexual orientation, disability, religion or belief, age 
        or any other grounds.</p>

<p>B) Shopsy prohibits discrimination against delivery partners under any circumstances and on any grounds including on the basis of race, religion, caste, place of 
    origin, disability, sexual orientation, sex, marital status, gender identity, age, or any other characteristics that may be protected under applicable law.</p>

<p>C) We reserve the right to withhold access to the Platform and otherwise limit Your access to the Platform at Our absolute discretion if You behave towards any 
    delivery partner working with Shopsy in a manner which is discourteous, disrespectful, or abusive, or which otherwise may be deemed to be inappropriate or 
    unlawful.</p>

<p>D) You are expected to treat all delivery partners with courtesy and respect.</p>

<p>Shopsy s Replacement Guarantee</p>

<p>Shopsy 's Replacement Guarantee seeks to assist Buyers who have been defrauded by qualified sellers on the Platform. The return policy period (Shopsy's Replacement 
    Guarantee) depends on the product category and the seller. Kindly click here to know the return policy period applicable for different categories. If at the time 
    of delivery and/or within the applicable return policy period, if any defect is found, then the buyer of the product/s can ask for replacement of the product/s 
    from the seller subject to the following terms and conditions.</p>

<ul class="outer">
    <li>Notify the seller of any defects in the product/s at the time of delivery of the product/s and/or within the applicable return policy period and the same 
        product/s will be replaced in return of the defective product/s.</li>
<li>Replacement can be for the entire product/s or part/s of the product subject to availability of the same with the seller.</li>
</ul>

<p>The following products shall not be eligible for return or replacement:</p>

<p>a. Damages due to misuse of product.</p>

<p>b. Incidental damage due to malfunctioning of product.</p>

<p>c. Any consumable item which has been used/installed.</p>

<p>d. Products with tampered or missing serial/UPC numbers.</p>

<p>e. Digital products/services.</p>

<p>f. Any damage/defect which are not covered under the manufacturer's warranty.</p>

<p>g. Any product that is returned without all original packaging and accessories, including the box, manufacturer's packaging if any, and all other items originally 
    included with the product/s delivered.</p>

<p>h. Jewellery which is 'made to order' on customer's request.</p>

<p>On Clothing and Footwear, qualified sellers accept 30-day exchange subject to the following conditions:</p>

<p>Clothes and footwear are not used (other than for trial), altered, washed, soiled or damaged in any way.</p>

<p>Original tags and packaging should be intact. For items that come in branded packaging, the box should be undamaged.</p>

<p>Returns are not applicable for 'Made to order' jewellary, innerwear, lingerie, socks, clothing freebies, etc.</p>

<p>If Shopsy has any suspicion or knowledge that any of its buyers and sellers are involved in any activity that is intended to provide claims or information that is 
    false or not genuine, Shopsy may also, while reserving its rights to initiate civil and/or criminal proceedings against such member buyers and sellers, at its sole 
    discretion, suspend, block, restrict, cancel the Display Name of such buyers and sellers and/or disqualify that user and any related users from availing protection 
    through this program. Customers who have been blocked for any suspicious or fraudulent activity on Shopsy will not be allowed to return their products.</p>

<p>Shopsy reserves its right to initiate civil and/or criminal proceedings against a user who files an invalid and/or false claims or provides false, incomplete, or 
    misleading information. In addition to the legal proceedings as aforesaid, Shopsy may at its sole discretion suspend, block, restrict, cancel the Display Name 
    [and its related Display Names] of such user and/or disqualify that user and any related users from availing protection through this program. Any person who, 
    knowingly and with intent to injure, defraud or deceive, files a Fraudulent Complaint containing false, incomplete, or misleading information may be guilty of a 
    criminal offence and will be prosecuted to the fullest extent of the law.</p>

<p>Indemnity</p>

<p>You shall indemnify and hold harmless Shopsy, its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, 
    directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or 
    arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including 
    infringement of intellectual property rights) of a third party.</p>

<p>Applicable Law</p>

<p>Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be exclusively in Bangalore.</p>

<p>Jurisdictional Issues/Sale in India Only</p>

<p>Unless otherwise specified, the material on the Platform is presented solely for the purpose of sale in India. Shopsy makes no representation that materials in 
    the Platform are appropriate or available for use in other locations/Countries other than India. Those who choose to access this site from other locations/Countries 
    other than India do so on their own initiative and Shopsy is not responsible for supply of products/refund for the products ordered from other locations/Countries 
    other than India, compliance with local laws, if and to the extent local laws are applicable.</p>

<p>Trademark, Copyright and Restriction</p>

<p>This site is controlled and operated by Shopsy and products are sold by respective Sellers. All material on this site, including images, illustrations, audio 
    clips, and video clips, are protected by copyrights, trademarks, and other intellectual property rights. Material on Platform is solely for Your personal, 
    non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by email or other electronic 
    means and whether directly or indirectly and You must not assist any other person to do so. Without the prior written consent of the owner, modification of the 
    materials, use of the materials on any other Platform or networked computer environment or use of the materials for any purpose other than personal, non-commercial 
    use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. Any use for which You receive any remuneration, whether in money 
    or otherwise, is a commercial use for the purposes of this clause.</p>

<p>Trademark complaint</p>

<p>Shopsy respects the intellectual property of others. In case You feel that Your Trademark has been infringed, you can write to Shopsy at infringement@flipkart.com</p>

<p>Product Description</p>

<p>Shopsy we do not warrant that Product description or other content of this Platform is accurate, complete, reliable, current, or error-free and assumes no liability 
    in this regard.</p>

<p>Limitation of Liability</p>

<p>IN NO EVENT SHALL SHOPSY BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THESE TERMS OF USE, EVEN IF USER HAS 
    BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.</p>

<p>Shopsy Image/Videos Rating and Review Program</p>

<ul class="outer">
    <li>By adding a review of the product(s) with pictures and/or videos of the product(s), you may be eligible to win an electronic gift voucher (EGV) worth up to 
         20 rupees.</li><br/>

<li>By adding a review, you acknowledge that the nature of the review will not affect your eligibility to stand a chance to win the EGV.</li><br/>

<li>Reviews must be genuine and based on your actual experience with the product.</li><br/>

<li>Reviews must comply with the Platform's guidelines and content policies, including those prohibiting offensive, abusive, or inappropriate content.</li><br/>

<li>Reviews must not contain any personal information, such as your name, address, phone number, or email address.</li><br/>

<li>Reviews must not promote products or services that were not purchased on Shopsy or its affiliate platforms.</li><br/>

<li>All reviews and ratings will be subject to moderation by the Platform.</li><br/>

<li>By participating in this program, you acknowledge that you have read, understood, and agree to these Terms and Conditions and the Platform Terms of Use.</li>
</ul><br/>

<p>Contact Us</p>

<p>Please contact us for any questions or comments (including all inquiries unrelated to copyright infringement) regarding this platform through the link:
     https://www.shopsy.in/rv/orders.</p>

<p>Grievance officer</p>

<p>In accordance with the Information Technology Act 2000 and rules made there under the Consumer Protection (E-Commerce) Rules, 2020, the name and contact details 
    of the Grievance Officer are provided below:</p>

<p>Mr. Shremanth M</p>

<p>Designation: Senior Manager</p>

<p>Flipkart Internet Pvt Ltd Block B (Begonia),</p>

<p>8th Floor Embassy Tech Village,</p>

<p>Outer Ring Road, Devarabeesanahalli Village,</p>

<p>Varthur Hobli, Bengaluru East Taluk,</p>

<p>Bengaluru District-560103, Karnataka:, India.</p>

<p>Contact us:</p>

<p>Email: grievanceofficer@shopsy.in</p>

<p>Phone: 044-45614700</p>

<p>Time: Mon - Sat (9:00 - 18:00)</p>

<p>Customer Support: You can reach our customer support team to address any of your queries or complaints by clicking the link, selecting your order and choosing 'Need 
    Help' option: https://www.shopsy.in/rv/orders</p>

<p>Policies</p>

<p>Profanity Policy</p>

<p>Shopsy prohibits the use of language that is racist, hateful, sexual or obscene in nature in a public area.</p>

<p>This policy extends to text within listings, on Seller pages and all other areas of the site that another User may view. If the profane words are part of a title 
    for the item being sold, we allow Sellers to 'blur' out the bulk of the offending word with asterisks (i.e., s*** or f***).</p>

<p>Please report any violations of this policy to the correct area for review:</p>

<ul class="outer">
    <li>Report offensive Display Names</li><br/>
<li>Report offensive language in a listing or otherwise.</li>

</ul><br/>

<p>If a feedback comment; or any communication made between Users on the Platform; or email communication between Users in relation to transactions conducted on 
    Platform contain profanity, please review Our feedback removal policy and submit a request for action/removal.</p>

<p>Disciplinary action may result in the indefinite suspension of a user's account, temporary suspension, or a formal warning.</p>

<p>Shopsy will consider the circumstances of an alleged policy violation and the user's trading records before taking action.</p>

<p>Violations of this policy may result in a range of actions, including:</p>

<ul class="outer">
    <li>Limits placed on account of privileges.</li><br/>
<li>Loss of special status.</li><br/>
<li>Account suspension.</li>
</ul><br/>
<p>Shopsy shall have the right to delete a product review posted by the customer at its sole discretion, if it is of the opinion that the review contains offensive 
    language as stated above. Further, if Shopsy is of the opinion that the review unfairly either: (i) causes disadvantage to a product; or (ii) increases the 
    popularity of the product, Shopsy shall have the right to delete the customer review. Shopsy shall also, at its sole discretion, have the right to blacklist the 
    customer from posting any further customer reviews.</p>
        </div>
    </div>
    )

    }

export default Terms;